### ISSUE TITLE
Créer une base de données sur Firebase

### ISSUE THREAD

**Issue by hadeli** [hadeli/boat-tracker#10]
- [ ] Se connecter à Firebase

- [ ] Créer une base de données

Créer le modèle de la façon suivante :
![capture du 2019-03-06 13-57-46](https://user-images.githubusercontent.com/3610089/53883270-cfba5a00-4018-11e9-8655-bc4bd2439a5c.png)
![capture du 2019-03-06 13-58-04](https://user-images.githubusercontent.com/3610089/53883277-d2b54a80-4018-11e9-9380-dca0af6d9c62.png)

![capture du 2019-03-06 13-58-31](https://user-images.githubusercontent.com/3610089/53883294-dd6fdf80-4018-11e9-9659-8a454255be14.png)

![capture du 2019-03-06 13-58-47](https://user-images.githubusercontent.com/3610089/53883305-e365c080-4018-11e9-8eb7-6e78e0bfb088.png)

**Comment by Xartrick** [comment]
Dans le modèle `containership`, il manque la relation `type` (qui pointe sur `containership-type`).
